### PR TITLE
Fix error message

### PR DESCRIPTION
**Pull request by jordanschalm**

### CODE REVIEW

**Review by joshuahannan — APPROVED** [review]
Looks good to me! Make sure you run `make test` to rebuild the contracts

**Comment by jordanschalm** [comment]
```
git diff --exit-code
bash build_crypto_dependency.sh
chmod: cannot access '/home/runner/go/pkg/mod/github.com/onflow/flow-go/crypto@v0.21.3': No such file or directory
build_crypto_dependency.sh: line 17: cd: /home/runner/go/pkg/mod/github.com/onflow/flow-go/crypto@v0.21.3: No such file or directory
go test ./... --tags relic
# github.com/onflow/flow-go/crypto
In file included from /home/runner/go/pkg/mod/github.com/onflow/flow-go/crypto@v0.23.3/bls.go:32:
Error: /home/runner/go/pkg/mod/github.com/onflow/flow-go/crypto@v0.23.3/bls_include.h:8:10: fatal error: relic.h: No such file or directory
    8 | #include "relic.h"
      |          ^~~~~~~~~
compilation terminated.
```

Have you seen this on before @joshuahannan ?

**Comment by joshuahannan** [comment]
hmm. I haven't seen that before, but I just tried it and that happened to me. Not really sure why though. @tarakby might have an idea?

**Comment by tarakby** [comment]
I'll look at the branch and make a commit shortly

**Comment by tarakby** [comment]
If you upgrade the crypto lib version, we need to mirror it here as well : https://github.com/onflow/flow-core-contracts/blob/jordan/hf/fix-error-msg/lib/go/test/build_crypto_dependency.sh#L7-L9

It's manual for now, but there is a PR to change this in flow-go, and it's gonna be updated in flow-core-contract too.

**Pull request merged**
