### PR TITLE
WIP: Replace deprecated `flow-go/crypto` 

### PR DESCRIPTION
**Pull request by tarakby**
replace the deprecated module `onflow/flow-go/crypto` by `onflow/crypto`

### CODE REVIEW

**Review by joshuahannan — APPROVED** [review]

**Comment by joshuahannan** [comment]
@tarakby Do you need help getting CI passing? I can take a look. I know the tests are unwieldy to say the least

**Comment by tarakby** [comment]
> Do you need help getting CI passing?

Yes please, if you can at least find out what went wrong and I can fix it. I noticed the failing tests do not pass locally on the master branch either, so I'm not sure what's wrong. No need to prioritize though, this PR is not blocking any other work.

**Comment by joshuahannan** [comment]
@tarakby It looks like with the new crypto library, the public key that is being created for the tests is deemed invalid by the `FlowIDTableStaking` smart contract. You can validate by navigating to the `lib/go/test` directory and running `go test -v -run TestIDTableRegistration`. The first error that pops up is:
```
    test.go:184: 
        	Error Trace:	/Users/joshuahannan/dapperlabs/flow/flow-core-contracts/lib/go/test/test.go:184
        	            				/Users/joshuahannan/dapperlabs/flow/flow-core-contracts/lib/go/test/test.go:161
        	            				/Users/joshuahannan/dapperlabs/flow/flow-core-contracts/lib/go/test/staking_test_helpers.go:394
        	            				/Users/joshuahannan/dapperlabs/flow/flow-core-contracts/lib/go/test/flow_idtable_staking_test.go:414
        	Error:      	Should be true
        	Test:       	TestIDTableRegistration/Should_be_able_to_create_a_valid_Node_struct_and_not_create_duplicates
    test.go:185: [Error Code: 1101] error caused by: 1 error occurred:
        	* transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
          --> 0b75eef7ca66b81fa68ae6b33c117a48cc1989d726c12a249fc63715094941a0:23:26
           |
        23 |         let nodeStaker <- FlowIDTableStaking.addNodeRecord(
        24 |             id: id,
        25 |             role: role,
        26 |             networkingAddress: networkingAddress,
        27 |             networkingKey: networkingKey,
        28 |             stakingKey: stakingKey,
        29 |             tokensCommitted: <-self.flowTokenRef.withdraw(amount: amount)
        30 |         )
           |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
            --> 179b6b1cb6755e31.FlowIDTableStaking:1544:30
             |
        1544 |         let newNode <- create NodeRecord(id: id,
        1545 |                                          role: role,
        1546 |                                          networkingAddress: networkingAddress,
        1547 |                                          networkingKey: networkingKey,
        1548 |                                          stakingKey: stakingKey,
        1549 |                                          tokensCommitted: <-FlowToken.createEmptyVault())
             |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
        error: invalid public key: [129, 144, 20, 35, 175, 229, 228, 241, 208, 59, 80, 60, 41, 20, 171, 7, 17, 98, 141, 79, 153, 19, 202, 5, 204, 188, 6, 144, 214, 64, 90, 134, 234, 84, 249, 205, 167, 203, 167, 170, 108, 176, 190, 140, 5, 164, 115, 228, 0, 140, 162, 79, 166, 173, 55, 19, 210, 109, 193, 188, 173, 14, 189, 241, 55, 7, 156, 62, 144, 96, 31, 210, 152, 62, 155, 56, 126, 194, 180, 201, 77, 247, 193, 101, 114, 24, 13, 172, 145, 141, 218, 191, 38, 5, 193, 134], err: decode public key failed: the signature scheme BLS_BLS12381 is not supported
           --> 179b6b1cb6755e31.FlowIDTableStaking:185:27
            |
        185 |             let stakeKey = PublicKey(
        186 |                 publicKey: stakingKey.decodeHex(),
        187 |                 signatureAlgorithm: SignatureAlgorithm.BLS_BLS12_381
        188 |             )
            |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

So apparently `BLS_BLS12381` is not supported? The keys are generated here: https://github.com/onflow/flow-core-contracts/blob/tarak/use-onflow-crypto/lib/go/test/staking_test_helpers.go#L296

Does that need to change or does the smart contract need to change?

**Comment by joshuahannan** [comment]
@tarakby thanks for updating the dependencies. I pushed another commit to get the CI to pass. We're removing the JS tests because they are unreliable.

**Comment by tarakby** [comment]
@joshuahannan Thanks for continuing the work! I didn't notice the PR got merged till now 😅. Meanwhile I made this [commit](https://github.com/onflow/flow-core-contracts/commit/6334711f356f4bd906b14623373f267f243e252d) to fix the Go version to 1.20. 
I leave two comments about [the last commit](https://github.com/onflow/flow-core-contracts/pull/409/commits/23026673f0300e9b6903eacfa6ae892a02d695a1):
- it bumps Go to 1.21 while all `onflow/` repos work with 1.20. It worked for now but it's not guaranteed to work with other versions.
- the `lib/go/tests/go.mod` and `lib/go/contracts/go.mod` still use 1.18

**Pull request merged**
