### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by janezpodhostnik**
Upgrade dependencies and go version

prerequisite for: https://github.com/onflow/flow-go/issues/2767

### CODE REVIEW

**Comment by janezpodhostnik** [comment]
I'm hitting a badger problem when running the tests originating from the emulator I think (you can also see them in CI)

```
            	Error Trace:	/home/runner/work/flow-core-contracts/flow-core-contracts/lib/go/test/test.go:174
            	            				/home/runner/work/flow-core-contracts/flow-core-contracts/lib/go/test/test.go:146
            	            				/home/runner/work/flow-core-contracts/flow-core-contracts/lib/go/test/flow_idtable_nodes_test.go:485
            	Error:      	Received unexpected error:
            	            	Txn is too big to fit into one request
            	            	github.com/dgraph-io/badger/v2.init
            	            		/home/runner/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.4/errors.go:39
            	            	runtime.doInit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:6321
            	            	runtime.doInit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:6298
            	            	runtime.doInit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:6298
            	            	runtime.doInit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:6298
            	            	runtime.doInit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:6298
            	            	runtime.doInit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:6298
            	            	runtime.doInit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:6298
            	            	runtime.main
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/proc.go:233
            	            	runtime.goexit
            	            		/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/asm_amd64.s:1594
```

I have no Idea why this would happen and how to fix it. I was hoping if anyone has any ideas before I go into research mode. @sideninja maybe?

**Comment by joshuahannan** [comment]
@janezpodhostnik We can honestly probably remove that whole test ("Should be able to register many delegators"). I was only using it to test gas usage for the end epoch transactions, but it doesn't actually test any important functionality. It just registers something like 10k delegators, which will never happen in real life.

**Review by joshuahannan — APPROVED** [review]
Looks fine to me!

**Comment by janezpodhostnik** [comment]
@joshuahannan I didn't remove the test, I just reduced the numbers.

**Pull request merged**
